config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root :to => redirect('/batteries')

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get :lookup_upc, to: "ext_data#lookup_upc_code"

      scope "/scanner/:id", controller: :scanners do
        get "/", action: :show
      end
      scope "/scanners", controller: :scanners do
        get "/", action: :index
        get "/known_models", action: :known_models
      end

      scope "/thing/:id", controller: :things do
        get "/", action: :show
      end
      scope "/things", controller: :things do
        get "/", action: :index
        post "/search", action: :index
      end
    end
    get "*", to: "api#not_found"
  end

  scope :constraints => { :format => 'html' } do
    get "mobile_scanner", to: "ui#mobile_scanner"
    get "*path", to: "ui#catchall"
  end
end

app/models/battery.rb
class Battery < ApplicationRecord
  belongs_to :current_device, class_name: "Device", optional: true

  PATTERN = /^(LI|NiMH|LFP)-/

  BRAND_MAP = {
    "PB" => "PaleBlue",
    "AT" => "AmpTorrent",
    "Tn" => "Tenergy",
  }

  has_paper_trail(
    only: %i[current_device_id]
  )

  def brand_name
    BRAND_MAP[parsed_id[:brand]] || "Unknown"
  end

  def chemistry
    parsed_id[:chemistry]
  end

  def size
    parsed_id[:size]
  end

  def parsed_id
    bits = id.split("-")
    {
      chemistry: bits[0],
      size: bits[1],
      brand: bits[2],
      instance: bits[3]
    }
  end
end

app/helpers/batteries_helper.rb
module BatteriesHelper
end

app/views/batteries/index.html.erb
<table class="ui celled table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Current Device</th>
      <th>Last Checkin</th>
    </tr>
  </thead>
  <tbody>
    <% @batteries.each do |battery| %>
      <tr>
        <td>
          <a href="<%= battery_path(battery) %>">
            <%= battery.id %>
          </a>
        </td>
        <td>
          <% if battery.current_device.present? %>
            <a href="<%= device_path(battery.current_device) %>">
              <div style="display: flex;">
                <div>
                  <i class="mobile alternate icon"></i>
                </div>
                <div>
                  <strong>
                    <%= battery.current_device.human_name || battery.current_device.id %>
                  </strong><br>
                  <small class="text-muted" style="margin-left: 6px;">
                    <%= battery.current_device.id %>
                  </small>
                </div>
              </div>
            </a>
          <% else %>
            -
          <% end %>
        </td>
        <td>
          <%= local_time(battery.updated_at) %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/batteries/show.html.erb
<h1>
  <%= @battery.id %>
</h1>

<div class="ui grid">
  <div class="four wide column">
    <div class="ui segment">
      <h4 class="ui header">Info</h4>
      <div class="ui list">
        <div class="item">
          <strong>ID:</strong>
          <%= @battery.id %>
        </div>
        <% @battery.parsed_id.each do |key, value| %>
          <div class="item">
            <strong>
              <%= key.to_s.titleize %>:
            </strong> <code><%= value %></code>
          </div>
        <% end %>
        <div class="item">
          <strong>First Seen:</strong>
          <%= local_time(@battery.created_at) %>
        </div>
      </div>
    </div>

    <% device=@battery.current_device %>
    <% if device.present? %>
      <div class="ui segment">
        <div style="display: flex;">
          <h4 class="ui header" style="flex: 1; margin-bottom: 0;;">Current Device</h4>
          <a href="<%= device_path(device) %>">
            <i class="external alternate icon" style="margin-left: 8px;"></i>
          </a>
        </div>
        <div class="ui list">
          <% if device.human_name.present? %>
            <div class="item">
              <strong>Name:</strong> <a href="<%= device_path(device) %>">
                <%= device.human_name %>
              </a>
            </div>
          <% end %>

          <div class="item">
            <strong>ID:</strong>
            <%= device.id %>
          </div>

          <div class="item">
            <strong>Since:</strong>
            <%= local_time(@battery.versions.last.created_at) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="twelve wide column">
    <div class="ui segment">
      <h4 class="ui header">History</h4>
      <table class="ui very basic celled table">
        <tbody>
          <% @battery.versions.reverse.each do |version| %>
            <tr>
              <td>
                <%= local_time(version.created_at) %>
              </td>
              <td>
                <% snapshot = version.reify %>
                <% if snapshot&.current_device.present? %>
                  <a href="<%= device_path(snapshot.current_device) %>">
                    <div style="display: flex;">
                      <div>
                        <i class="mobile alternate icon"></i>
                      </div>
                      <div>
                        <strong>
                          <%= snapshot.current_device.human_name || snapshot.current_device.id %>
                        </strong><br>
                        <small class="text-muted" style="margin-left: 6px;">
                          <%= snapshot.current_device.id %>
                        </small>
                      </div>
                    </div>
                  </a>
                <% else %>
                  -
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>